image:
  repository: dievri/9mine-lua-fs
  pullPolicy: Always
  tag: "main"

service:
  type: ClusterIP
  port: 2626

fs: |
  {% include 'common.j2' %}
  wrapper_name: lua

  fs:
    "/":
      name: root
      readdir: |
        echo .include.lua
        echo directory
      getattr: *dir
      "/.include.lua":
        name: lua_include_file
        getattr: *file
        read_file: |
            cat <<EOF
            say_hello = function(player_name, message)
            minetest.chat_send_all("Hello from LUA-FS service")
            end
            table.insert(functions, say_hello)
            filter = function(entry_path, entity)
            if entry_path:match("^REPLACE_ME/%.?[%w]+%.lua") then
                entity:set_properties({
                    textures = {"core_lua.png"}
                })
                return "core_lua.png"
            end
            if entry_path:match("^REPLACE_ME/") then
              local lua_entity = entity:get_luaentity()
                lua_entity.visual = "cube"
                entity:set_properties({
                    visual = "cube",
                    textures = {"core_console.png", "core_console.png", "core_console.png", "core_console.png",
                                "core_console.png", "core_console.png"}
                })
                return "core_console.png"
            end
            end
            table.insert(filters, filter)
            craft = function(itemstack, player, old_craft_grid, craft_inv)
                if itemstack:get_name() == "core:service_node" and old_craft_grid[1]:get_name() == "core:service_node" and
                    old_craft_grid[2]:get_name() == "core:file_node" then
                    local inventory = player.get_inventory(player)
                    inventory:add_item("main", old_craft_grid[1])
                    inventory:add_item("main", old_craft_grid[2])
                    -- get info from service
                    local service_meta = old_craft_grid[1]:get_meta()
                    local service_path = service_meta:get_string("path")
                    -- get info from file 
                    local file_meta = old_craft_grid[2]:get_meta()
                    local file_path = file_meta:get_string("path")
                    -- set crafted item meta 
                    minetest.chat_send_all("cp " .. file_path .. " -> " .. service_path)
                    itemstack:take_item()
                end
            end
            table.insert(crafts, craft)
            EOF
      "/directory":
        name: subroot
        getattr: *dir
        readdir:
